#!/usr/bin/env python3
"""
Phase 38C.1T.1 — Create Canonical Administrative Excel Template.

Creates data/templates/student_parent_timetable_template.xlsx with 5 sheets:
1. STUDENTS - enrollment contract (student_id canonical)
2. PARENTS - Parent Registry contract
3. STUDENT_PARENTS - many-to-many links
4. TIMETABLE - TimetableLoader compatible schema
5. TELEGRAM_CONFIG_GUIDE - configuration guide only (no secrets)
"""

from __future__ import annotations

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from pathlib import Path


def create_workbook() -> openpyxl.Workbook:
    """Create the administrative template workbook."""
    wb = openpyxl.Workbook()
    
    # Style definitions
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    example_fill = PatternFill(start_color="E2EFDA", end_color="E2EFDA", fill_type="solid")
    warning_fill = PatternFill(start_color="FCE4D6", end_color="FCE4D6", fill_type="solid")
    thin_border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    
    def style_header_row(ws, row=1, max_col=None):
        if max_col is None:
            max_col = ws.max_column
        for col in range(1, max_col + 1):
            cell = ws.cell(row=row, column=col)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment
            cell.border = thin_border
    
    def style_data_rows(ws, start_row=2, max_col=None, fill=None):
        if max_col is None:
            max_col = ws.max_column
        for row in range(start_row, ws.max_row + 1):
            for col in range(1, max_col + 1):
                cell = ws.cell(row=row, column=col)
                cell.border = thin_border
                if fill:
                    cell.fill = fill
    
    def auto_width(ws, min_width=12, max_width=40):
        for col in ws.columns:
            max_length = 0
            column_letter = get_column_letter(col[0].column)
            for cell in col:
                try:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))
                except:
                    pass
            adjusted_width = min(max(max_length + 2, min_width), max_width)
            ws.column_dimensions[column_letter].width = adjusted_width
    
    # =========================================================================
    # SHEET 1: STUDENTS
    # =========================================================================
    ws_students = wb.active
    ws_students.title = "STUDENTS"
    
    students_headers = [
        "student_id",           # Canonical identity (matches enrollment DB person_id)
        "student_name",         # Human-readable name
        "class_name",           # Class/grade (e.g., "10A", "11B")
        "enrollment_status",    # active, inactive, graduated, transferred
        "notes",                # Free text notes
    ]
    
    for col_idx, header in enumerate(students_headers, 1):
        ws_students.cell(row=1, column=col_idx, value=header)
    
    # Example rows (clearly marked)
    example_students = [
        ["HS001", "Nguyen Van An", "10A", "active", "Example student - REPLACE WITH REAL DATA"],
        ["HS002", "Tran Thi Binh", "10A", "active", "Example student - REPLACE WITH REAL DATA"],
        ["HS003", "Le Van Cuong", "11B", "active", "Example student - REPLACE WITH REAL DATA"],
    ]
    
    for row_idx, row_data in enumerate(example_students, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws_students.cell(row=row_idx, column=col_idx, value=value)
    
    style_header_row(ws_students)
    style_data_rows(ws_students, fill=example_fill)
    auto_width(ws_students)
    
    # Add note row
    note_row = len(example_students) + 2
    ws_students.cell(row=note_row, column=1, value="NOTE: student_id MUST match enrollment database person_id exactly.")
    ws_students.cell(row=note_row, column=1).font = Font(italic=True, color="FF0000")
    ws_students.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=len(students_headers))
    
    # =========================================================================
    # SHEET 2: PARENTS
    # =========================================================================
    ws_parents = wb.create_sheet("PARENTS")
    
    parents_headers = [
        "parent_id",              # Auto-generated by ParentRegistry (PAR-xxxxxxxx)
        "parent_name",            # Full name of parent/guardian
        "relationship",           # parent, guardian, emergency_contact, etc.
        "telegram_username",      # Telegram @username (optional, for reference only)
        "telegram_profile_link",  # Telegram profile link (optional, for reference only)
        "telegram_chat_id",       # REQUIRED for notifications - numeric chat ID from /start flow
        "telegram_enabled",       # true/false - whether to send Telegram notifications
        "notification_preferences", # all, morning_absence_only, long_exit_only, missing_checkout_only, none
        "notes",                  # Free text notes
    ]
    
    for col_idx, header in enumerate(parents_headers, 1):
        ws_parents.cell(row=1, column=col_idx, value=header)
    
    example_parents = [
        ["PAR-ABC12345", "Nguyen Van An (Father)", "parent", "@nguyen_an", "https://t.me/nguyen_an", "123456789", "true", "all", "Example parent - REPLACE WITH REAL DATA"],
        ["PAR-BCD23456", "Tran Thi Binh (Mother)", "parent", "@tran_binh", "https://t.me/tran_binh", "987654321", "true", "all", "Example parent - REPLACE WITH REAL DATA"],
        ["PAR-CDE34567", "Le Van Cuong (Guardian)", "guardian", "", "", "", "true", "morning_absence_only", "Example guardian - REPLACE WITH REAL DATA"],
    ]
    
    for row_idx, row_data in enumerate(example_parents, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws_parents.cell(row=row_idx, column=col_idx, value=value)
    
    style_header_row(ws_parents)
    style_data_rows(ws_parents, fill=example_fill)
    auto_width(ws_parents)
    
    note_row = len(example_parents) + 2
    ws_parents.cell(row=note_row, column=1, value="NOTE: telegram_chat_id is the ONLY routing identifier. Username/profile_link are for reference only.")
    ws_parents.cell(row=note_row, column=1).font = Font(italic=True, color="FF0000")
    ws_parents.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=len(parents_headers))
    
    note_row2 = note_row + 1
    ws_parents.cell(row=note_row2, column=1, value="NOTE: parent_id is auto-generated by ParentRegistry (format: PAR-xxxxxxxx). Do not manually assign.")
    ws_parents.cell(row=note_row2, column=1).font = Font(italic=True, color="FF0000")
    ws_parents.merge_cells(start_row=note_row2, start_column=1, end_row=note_row2, end_column=len(parents_headers))
    
    # =========================================================================
    # SHEET 3: STUDENT_PARENTS
    # =========================================================================
    ws_links = wb.create_sheet("STUDENT_PARENTS")
    
    links_headers = [
        "link_id",                # Auto-generated by ParentRegistry (LNK-xxxxxxxx)
        "student_id",             # Canonical student_id (matches STUDENTS sheet)
        "parent_id",              # Parent ID from PARENTS sheet
        "relationship",           # parent, guardian, emergency_contact, etc.
        "is_primary",             # true/false - primary contact for notifications
        "notes",                  # Free text notes
    ]
    
    for col_idx, header in enumerate(links_headers, 1):
        ws_links.cell(row=1, column=col_idx, value=header)
    
    example_links = [
        ["LNK-ABC12345", "HS001", "PAR-ABC12345", "parent", "true", "Example link - REPLACE WITH REAL DATA"],
        ["LNK-BCD23456", "HS001", "PAR-BCD23456", "parent", "false", "Example link - REPLACE WITH REAL DATA"],
        ["LNK-CDE34567", "HS002", "PAR-BCD23456", "parent", "true", "Example link - REPLACE WITH REAL DATA"],
        ["LNK-DEF45678", "HS003", "PAR-CDE34567", "guardian", "true", "Example link - REPLACE WITH REAL DATA"],
    ]
    
    for row_idx, row_data in enumerate(example_links, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws_links.cell(row=row_idx, column=col_idx, value=value)
    
    style_header_row(ws_links)
    style_data_rows(ws_links, fill=example_fill)
    auto_width(ws_links)
    
    note_row = len(example_links) + 2
    ws_links.cell(row=note_row, column=1, value="NOTE: Many-to-many relationship preserved. One student can have multiple parents; one parent can have multiple students.")
    ws_links.cell(row=note_row, column=1).font = Font(italic=True, color="FF0000")
    ws_links.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=len(links_headers))
    
    note_row2 = note_row + 1
    ws_links.cell(row=note_row2, column=1, value="NOTE: link_id is auto-generated by ParentRegistry (format: LNK-xxxxxxxx). Do not manually assign.")
    ws_links.cell(row=note_row2, column=1).font = Font(italic=True, color="FF0000")
    ws_links.merge_cells(start_row=note_row2, start_column=1, end_row=note_row2, end_column=len(links_headers))
    
    # =========================================================================
    # SHEET 4: TIMETABLE
    # =========================================================================
    ws_timetable = wb.create_sheet("TIMETABLE")
    
    # TimetableLoader REQUIRED columns (must be present for load_from_excel to work)
    required_cols = [
        "student_id",       # Canonical student/business identifier (matches enrollment DB)
        "class_name",       # Class/session name (e.g., "Toan 10A", "Ly 10A")
        "day",              # Day of week (monday, tuesday, wednesday, thursday, friday, saturday, sunday)
        "session_type",     # classroom, break, outside_lesson, lab, other, morning, afternoon, full_day, evening
        "entry_time",       # Expected entry time (HH:MM:SS or seconds from midnight)
        "exit_time",        # Expected exit time (HH:MM:SS or seconds from midnight)
    ]
    
    # TimetableLoader OPTIONAL columns (with defaults)
    optional_cols = [
        "session_id",           # Auto-generated if not provided (format: CLASSNAME_DAY)
        "person_name",          # Human-readable name (optional)
        "subject",              # Subject name (e.g., Toan, Ly, Hoa, GDTC)
        "location",             # Physical location (e.g., Phòng 101, Sân thể dục)
        "expected_location",    # Expected location for outside lessons
        "outside_allowed",      # true/false - whether students allowed outside classroom
        "entry_window_start",   # Defaults to entry_time - 300s (5 min)
        "entry_window_end",     # Defaults to entry_time + 300s (5 min)
        "late_tolerance",       # Default 600s (10 min) - seconds after entry_time considered late
        "exit_window_start",    # Defaults to exit_time - 300s (5 min)
        "exit_window_end",      # Defaults to exit_time + 300s (5 min)
        "timetable_version",    # Version string (default "1.0")
    ]
    
    all_timetable_cols = required_cols + optional_cols
    
    for col_idx, header in enumerate(all_timetable_cols, 1):
        ws_timetable.cell(row=1, column=col_idx, value=header)
    
    # Example timetable data (matching TimetableLoader expectations)
    example_timetable = [
        # HS001 - Monday
        ["HS001", "Toan 10A", "monday", "classroom", "07:00:00", "11:30:00", "TOAN10A_MON", "Nguyen Van An", "Toan", "Phòng 101", "", "false", "", "", "600", "", "", "1.0"],
        ["HS001", "Ly 10A", "monday", "classroom", "13:00:00", "15:30:00", "LY10A_MON", "Nguyen Van An", "Ly", "Phòng 102", "", "false", "", "", "600", "", "", "1.0"],
        # HS001 - Tuesday
        ["HS001", "Hoa 10A", "tuesday", "lab", "07:00:00", "11:30:00", "HOA10A_TUE", "Nguyen Van An", "Hoa", "Phòng Lab 1", "", "false", "", "", "600", "", "", "1.0"],
        ["HS001", "GDTC 10A", "tuesday", "outside_lesson", "13:00:00", "15:30:00", "GDTC10A_TUE", "Nguyen Van An", "GDTC", "Sân thể dục", "Sân thể dục", "true", "", "", "600", "", "", "1.0"],
        # HS002 - Monday
        ["HS002", "Toan 10A", "monday", "classroom", "07:00:00", "11:30:00", "TOAN10A_MON", "Tran Thi Binh", "Toan", "Phòng 101", "", "false", "", "", "600", "", "", "1.0"],
        ["HS002", "Van 10A", "monday", "classroom", "13:00:00", "15:30:00", "VAN10A_MON", "Tran Thi Binh", "Van", "Phòng 103", "", "false", "", "", "600", "", "", "1.0"],
        # HS002 - Wednesday
        ["HS002", "Anh 10A", "wednesday", "classroom", "07:00:00", "11:30:00", "ANH10A_WED", "Tran Thi Binh", "Anh", "Phòng 104", "", "false", "", "", "600", "", "", "1.0"],
        # HS003 - Monday
        ["HS003", "Toan 11B", "monday", "classroom", "07:00:00", "11:30:00", "TOAN11B_MON", "Le Van Cuong", "Toan", "Phòng 201", "", "false", "", "", "600", "", "", "1.0"],
        ["HS003", "Ly 11B", "monday", "classroom", "13:00:00", "15:30:00", "LY11B_MON", "Le Van Cuong", "Ly", "Phòng 202", "", "false", "", "", "600", "", "", "1.0"],
    ]
    
    for row_idx, row_data in enumerate(example_timetable, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws_timetable.cell(row=row_idx, column=col_idx, value=value)
    
    style_header_row(ws_timetable)
    style_data_rows(ws_timetable, fill=example_fill)
    auto_width(ws_timetable)
    
    # Add important notes
    note_row = len(example_timetable) + 2
    ws_timetable.cell(row=note_row, column=1, value="IMPORTANT: This sheet uses the EXACT schema accepted by TimetableLoader.load_from_excel()")
    ws_timetable.cell(row=note_row, column=1).font = Font(bold=True, color="FF0000")
    ws_timetable.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=len(all_timetable_cols))
    
    note_row2 = note_row + 1
    ws_timetable.cell(row=note_row2, column=1, value="REQUIRED columns (must be present): student_id, class_name, day, session_type, entry_time, exit_time")
    ws_timetable.cell(row=note_row2, column=1).font = Font(italic=True, color="FF0000")
    ws_timetable.merge_cells(start_row=note_row2, start_column=1, end_row=note_row2, end_column=len(all_timetable_cols))
    
    note_row3 = note_row + 2
    ws_timetable.cell(row=note_row3, column=1, value="session_type values: classroom, break, outside_lesson, lab, other, morning, afternoon, full_day, evening")
    ws_timetable.cell(row=note_row3, column=1).font = Font(italic=True)
    ws_timetable.merge_cells(start_row=note_row3, start_column=1, end_row=note_row3, end_column=len(all_timetable_cols))
    
    note_row4 = note_row + 3
    ws_timetable.cell(row=note_row4, column=1, value="day values: monday, tuesday, wednesday, thursday, friday, saturday, sunday (abbreviations: mon, tue, wed, thu, fri, sat, sun)")
    ws_timetable.cell(row=note_row4, column=1).font = Font(italic=True)
    ws_timetable.merge_cells(start_row=note_row4, start_column=1, end_row=note_row4, end_column=len(all_timetable_cols))
    
    note_row5 = note_row + 4
    ws_timetable.cell(row=note_row5, column=1, value="Time format: HH:MM:SS or HH:MM or seconds from midnight (e.g., 07:00:00 or 25200)")
    ws_timetable.cell(row=note_row5, column=1).font = Font(italic=True)
    ws_timetable.merge_cells(start_row=note_row5, start_column=1, end_row=note_row5, end_column=len(all_timetable_cols))
    
    note_row6 = note_row + 5
    ws_timetable.cell(row=note_row6, column=1, value="outside_allowed: true/false - only relevant for session_type=outside_lesson")
    ws_timetable.cell(row=note_row6, column=1).font = Font(italic=True)
    ws_timetable.merge_cells(start_row=note_row6, start_column=1, end_row=note_row6, end_column=len(all_timetable_cols))
    
    # =========================================================================
    # SHEET 5: TELEGRAM_CONFIG_GUIDE
    # =========================================================================
    ws_telegram = wb.create_sheet("TELEGRAM_CONFIG_GUIDE")
    
    guide_headers = [
        "parameter_name",
        "description",
        "configuration_location",
        "placeholder_example",
        "security_warning",
    ]
    
    for col_idx, header in enumerate(guide_headers, 1):
        ws_telegram.cell(row=1, column=col_idx, value=header)
    
    guide_data = [
        [
            "TELEGRAM_BOT_TOKEN",
            "Telegram Bot API token from @BotFather. Used by the backend to send notifications.",
            "Environment variable ONLY (never in Excel, Git, or logs)",
            "123456789:ABCdefGhIJKlmNoPQRsTUVwxyZ",
            "CRITICAL: NEVER place real token in Excel. Set as environment variable: export TELEGRAM_BOT_TOKEN='your_token'",
        ],
        [
            "TELEGRAM_LIVE_TEST",
            "Enable live Telegram integration for testing. Set to 'true' to send real messages.",
            "Environment variable",
            "true",
            "Only enable in controlled test environments. Default: false",
        ],
        [
            "TELEGRAM_TEST_CHAT_ID",
            "Telegram chat ID for test notifications. Used when TELEGRAM_LIVE_TEST=true.",
            "Environment variable",
            "123456789",
            "Only for testing. Do not use production chat IDs.",
        ],
        [
            "telegram_chat_id (in PARENTS sheet)",
            "Per-parent Telegram chat ID for routing notifications. Obtained via /start <link_code> flow.",
            "PARENTS sheet column 'telegram_chat_id' (populated automatically after parent links via bot)",
            "123456789",
            "This is a routing identifier, not a secret. Populated by ParentRegistry after /start flow.",
        ],
        [
            "Link Code (XXXX-XXXX)",
            "Secure one-time code for parent to link their Telegram account. Generated by ParentRegistry.create_link_code().",
            "Generated programmatically, distributed to parents via secure channel (not Excel)",
            "A1B2-C3D4",
            "Treat as temporary secret. Expires after 24 hours (configurable). Single use only.",
        ],
    ]
    
    for row_idx, row_data in enumerate(guide_data, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws_telegram.cell(row=row_idx, column=col_idx, value=value)
    
    style_header_row(ws_telegram)
    style_data_rows(ws_telegram, fill=warning_fill)
    auto_width(ws_telegram, min_width=20, max_width=80)
    
    # Set row heights for readability
    for row in ws_telegram.iter_rows(min_row=2, max_row=len(guide_data)+1):
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    for row_idx in range(2, len(guide_data) + 2):
        ws_telegram.row_dimensions[row_idx].height = 60
    
    return wb


def validate_workbook(wb: openpyxl.Workbook, template_path: Path) -> dict:
    """Validate the created workbook."""
    results = {
        "sheets_exist": [],
        "headers_correct": {},
        "no_secrets": True,
        "timetable_loader_compatible": True,
        "errors": [],
        "warnings": [],
    }
    
    expected_sheets = ["STUDENTS", "PARENTS", "STUDENT_PARENTS", "TIMETABLE", "TELEGRAM_CONFIG_GUIDE"]
    
    # Check all sheets exist
    for sheet_name in expected_sheets:
        if sheet_name in wb.sheetnames:
            results["sheets_exist"].append(sheet_name)
        else:
            results["errors"].append(f"Missing sheet: {sheet_name}")
    
    # Check STUDENTS headers
    if "STUDENTS" in wb.sheetnames:
        ws = wb["STUDENTS"]
        headers = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
        expected = ["student_id", "student_name", "class_name", "enrollment_status", "notes"]
        results["headers_correct"]["STUDENTS"] = headers == expected
        if headers != expected:
            results["errors"].append(f"STUDENTS headers mismatch: got {headers}, expected {expected}")
    
    # Check PARENTS headers
    if "PARENTS" in wb.sheetnames:
        ws = wb["PARENTS"]
        headers = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
        expected = ["parent_id", "parent_name", "relationship", "telegram_username", "telegram_profile_link", 
                    "telegram_chat_id", "telegram_enabled", "notification_preferences", "notes"]
        results["headers_correct"]["PARENTS"] = headers == expected
        if headers != expected:
            results["errors"].append(f"PARENTS headers mismatch: got {headers}, expected {expected}")
    
    # Check STUDENT_PARENTS headers
    if "STUDENT_PARENTS" in wb.sheetnames:
        ws = wb["STUDENT_PARENTS"]
        headers = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
        expected = ["link_id", "student_id", "parent_id", "relationship", "is_primary", "notes"]
        results["headers_correct"]["STUDENT_PARENTS"] = headers == expected
        if headers != expected:
            results["errors"].append(f"STUDENT_PARENTS headers mismatch: got {headers}, expected {expected}")
    
    # Check TIMETABLE headers against TimetableLoader REQUIRED_COLUMNS
    if "TIMETABLE" in wb.sheetnames:
        ws = wb["TIMETABLE"]
        headers = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
        required = ["student_id", "class_name", "day", "session_type", "entry_time", "exit_time"]
        missing = [c for c in required if c not in headers]
        if missing:
            results["timetable_loader_compatible"] = False
            results["errors"].append(f"TIMETABLE missing required columns for TimetableLoader: {missing}")
        results["headers_correct"]["TIMETABLE"] = len(missing) == 0
    
    # Check TELEGRAM_CONFIG_GUIDE headers
    if "TELEGRAM_CONFIG_GUIDE" in wb.sheetnames:
        ws = wb["TELEGRAM_CONFIG_GUIDE"]
        headers = [ws.cell(row=1, column=c).value for c in range(1, ws.max_column + 1)]
        expected = ["parameter_name", "description", "configuration_location", "placeholder_example", "security_warning"]
        results["headers_correct"]["TELEGRAM_CONFIG_GUIDE"] = headers == expected
        if headers != expected:
            results["errors"].append(f"TELEGRAM_CONFIG_GUIDE headers mismatch: got {headers}, expected {expected}")
    
    # Check for secrets (real tokens, real chat IDs in example data)
    secret_patterns = [
        r"\d{8,10}:[A-Za-z0-9_-]{35}",  # Bot token pattern
    ]
    import re
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for row in ws.iter_rows(values_only=True):
            for cell_value in row:
                if cell_value and isinstance(cell_value, str):
                    for pattern in secret_patterns:
                        if re.search(pattern, cell_value):
                            results["no_secrets"] = False
                            results["warnings"].append(f"Potential secret found in {sheet_name}: {cell_value[:50]}...")
    
    # Check that example data doesn't have real-looking telegram_chat_id in PARENTS (should be placeholder)
    if "PARENTS" in wb.sheetnames:
        ws = wb["PARENTS"]
        for row in ws.iter_rows(min_row=2, values_only=True):
            chat_id = row[5]  # telegram_chat_id column
            if chat_id and str(chat_id).isdigit() and len(str(chat_id)) >= 9:
                # This is OK for example data, just warn
                results["warnings"].append(f"Example telegram_chat_id in PARENTS: {chat_id} (ensure replaced with real data)")
    
    return results


def main():
    template_path = Path("data/templates/student_parent_timetable_template.xlsx")
    
    print("Creating administrative Excel template...")
    wb = create_workbook()
    
    print("Validating workbook...")
    validation = validate_workbook(wb, template_path)
    
    print("Saving workbook...")
    wb.save(template_path)
    print(f"Saved to: {template_path}")
    
    # Print validation results
    print("\n=== VALIDATION RESULTS ===")
    print(f"Sheets found: {validation['sheets_exist']}")
    print(f"Headers correct: {validation['headers_correct']}")
    print(f"No secrets: {validation['no_secrets']}")
    print(f"TimetableLoader compatible: {validation['timetable_loader_compatible']}")
    if validation["errors"]:
        print(f"ERRORS: {validation['errors']}")
    if validation["warnings"]:
        print(f"WARNINGS: {validation['warnings']}")
    
    # Determine status
    if validation["errors"]:
        status = "BLOCKED"
    else:
        status = "CREATED_AND_VALIDATED"
    
    print(f"\nTEMPLATE_STATUS: {status}")
    print(f"EXACT_TEMPLATE_PATH: {template_path}")
    print("Phase 38C.2 = NOT STARTED")
    print("Phase 39 = NOT STARTED")
    
    return validation, status


if __name__ == "__main__":
    main()